#
# Copyright (C) 2016 DANS - Data Archiving and Networked Services (info@dans.knaw.nl)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- src: https://github.com/DANS-KNAW/dans.local-yum-repo
  version: v3.1.1
- src: https://github.com/DANS-KNAW/dans.local-test-vm-base
  version: v3.0.0
- src: https://github.com/DANS-KNAW/dans.easy-ldap-dir
  version: v3.0.1
- src: https://github.com/DANS-KNAW/dans.easy-test-users
  version: v1.2.0
- src: https://github.com/DANS-KNAW/dans.bagit
  version: v1.0.0
